//! High-quality audio engine for Willow Cricket — inspired by Big Ant Studios Cricket 26.
//! Provides tiered bat cracks, distinct wicket/catch/four/six reactions, pitch bounce,
//! layered crowd ambience and background music, plus Kenney CC0 UI feedback.
//! All synthesis is 44.1 kHz 16-bit mono WAV and runs without external files, but
//! menu UI also plays embedded CC0 OGG (Kenney) when available — see assets/audio/ATTRIBUTION.md.

use bevy::audio::{AudioPlayer, AudioSource, GlobalVolume, PlaybackSettings, Volume};
use bevy::ecs::system::SystemParam;
use bevy::prelude::*;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Resources
// ---------------------------------------------------------------------------

#[derive(Resource)]
pub struct SfxHandles {
    pub bat_light: Handle<AudioSource>,
    pub bat_heavy: Handle<AudioSource>,
    pub bat_edge: Handle<AudioSource>,
    pub wicket: Handle<AudioSource>,
    pub catch: Handle<AudioSource>,
    pub bounce: Handle<AudioSource>,
    pub cheer_four: Handle<AudioSource>,
    pub cheer_six: Handle<AudioSource>,
    pub ambient: Handle<AudioSource>,
    // fallback UI tones (used only if embedded OGG not yet ready)
    pub ui_fallback: Handle<AudioSource>,
}

// CC0 UI sounds loaded from embedded OGG — see assets/audio/ui/
#[derive(Resource)]
pub struct UiHandles {
    pub nav: Handle<AudioSource>,
    pub confirm: Handle<AudioSource>,
    pub back: Handle<AudioSource>,
    pub tick: Handle<AudioSource>,
    pub error: Handle<AudioSource>,
    pub bong: Handle<AudioSource>,
}

#[derive(Resource)]
pub struct MusicHandles {
    pub menu: Handle<AudioSource>,
    pub match_loop: Handle<AudioSource>,
}

#[derive(Resource, Default)]
pub struct CommentaryHandles {
    // role ("male" lead / "female" analyst) -> category -> Vec<Handle>
    pub male: HashMap<String, Vec<Handle<AudioSource>>>,
    pub female: HashMap<String, Vec<Handle<AudioSource>>>,
}

/// Real clip durations (seconds) from assets/audio/commentary/durations.json,
/// generated by scripts/generate_commentary_fixed.py. Keys are "role/file.ogg".
#[derive(Resource, Default)]
pub struct CommentaryDurations(pub HashMap<String, f32>);

/// Teams/overs recorded at match-session reset (metadata only; not used to
/// detect rematches).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct MatchFingerprint {
    pub teams: [usize; 2],
    pub overs: u32,
}

/// Once-per-match / once-per-innings lifecycle flags for phase commentary.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct CommentaryLifecycle {
    pub match_fp: Option<MatchFingerprint>,
    /// Set at every match-session reset; consumed when the welcome line is dispatched.
    pub match_intro_pending: bool,
    pub welcome_played: bool,
    /// While true, non-welcome commentary is deferred so the opening line is not talked over.
    pub intro_open: bool,
    pub deliveries_completed: u32,
    /// Innings number for which `innings_break` has already been called.
    pub innings_break_played_for: u8,
}

/// Priority for the commentary scheduler (lower = higher priority).
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum CommentaryPriority {
    /// Ball-result action lines (six, bowled, dot, …) — never displaced.
    Result = 0,
    /// Phase transitions (over end, innings break, match result).
    Phase = 1,
    /// Opening welcome — once per match, lowest priority.
    Welcome = 2,
}

#[derive(Clone, Debug)]
struct ScheduledCommentary {
    category: String,
    variant: Option<usize>,
    priority: CommentaryPriority,
}

/// Pending lead call waiting for a free audio slot (result beats phase beats welcome).
#[derive(Resource, Default)]
struct CommentaryScheduler {
    pending: Option<ScheduledCommentary>,
}

/// Tracks whether we are inside a `ResultPause` we have already processed
/// (reset on every `AppState::InMatch` entry).
#[derive(Resource, Default)]
struct CommentaryResultPauseEdge {
    in_result_pause: bool,
}

/// Tracks match-state facts so contextual lines only play when their facts
/// are known and true (per editorial rules).
#[derive(Resource)]
pub struct CommentaryHistory {
    pub last_category: String,
    pub last_indices: HashMap<String, usize>,
    pub lifecycle: CommentaryLifecycle,
    /// Last seen striker/bowler/team values for threshold-crossing detection.
    pub striker_runs: u32,
    pub team_runs: u32,
    pub rrr_last: Option<f32>,
    pub consecutive_dots: u32,
    /// Team runs at the start of the current over (for quiet/expensive over).
    pub over_start_runs: u32,
    pub over_start_valid: bool,
    /// Seconds until a routine call is allowed again (commentary gaps).
    pub routine_cooldown: f32,
}

impl Default for CommentaryHistory {
    fn default() -> Self {
        Self {
            last_category: String::new(),
            last_indices: HashMap::new(),
            lifecycle: CommentaryLifecycle::default(),
            striker_runs: 0,
            team_runs: 0,
            rrr_last: None,
            consecutive_dots: 0,
            over_start_runs: 0,
            over_start_valid: false,
            routine_cooldown: 0.0,
        }
    }
}

/// Smooth side-chain state for music/ambient ducking.
#[derive(Resource)]
pub struct CommentaryPlaying {
    /// Seconds left in the active clip (real duration from CommentaryDurations).
    pub remaining: f32,
    /// Queued analyst follow-up: (category, delay seconds).
    pub queued: Option<(String, f32)>,
    /// Current duck level 0..1 where 1 = no duck; eased toward target
    /// with fast attack / slow release like broadcast side-chaining.
    pub duck_level: f32,
}

impl Default for CommentaryPlaying {
    fn default() -> Self {
        Self {
            remaining: 0.0,
            queued: None,
            duck_level: 1.0,
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CommentaryVoice {
    Off,
    Male,
    Female,
}

#[derive(Resource, Clone)]
pub struct AudioSettings {
    pub master: f32,
    pub sfx: f32,
    pub music: f32,
    pub commentary: CommentaryVoice,
    pub commentary_volume: f32,
}

impl Default for AudioSettings {
    fn default() -> Self {
        Self {
            master: 0.85,
            sfx: 0.90,
            music: 0.70,
            commentary: CommentaryVoice::Male,
            commentary_volume: 0.85,
        }
    }
}

#[derive(Component)]
struct AmbientTag;
#[derive(Component)]
struct MusicMenuTag;
#[derive(Component)]
struct MusicMatchTag;

// ---------------------------------------------------------------------------
// WAV helpers
// ---------------------------------------------------------------------------

const SR: u32 = 44100;

fn wav_bytes(samples: &[f32], sample_rate: u32) -> Vec<u8> {
    let n = samples.len() as u32;
    let byte_rate = sample_rate * 2;
    let data_size = n * 2;
    let mut out = Vec::with_capacity(44 + data_size as usize);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36 + data_size).to_le_bytes());
    out.extend_from_slice(b"WAVE");
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes());
    out.extend_from_slice(&sample_rate.to_le_bytes());
    out.extend_from_slice(&byte_rate.to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes());
    out.extend_from_slice(&16u16.to_le_bytes());
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_size.to_le_bytes());
    for &s in samples {
        let v = (s.clamp(-1.0, 1.0) * 32767.0) as i16;
        out.extend_from_slice(&v.to_le_bytes());
    }
    out
}

#[inline]
fn env_adsr(t: f32, a: f32, d: f32, s: f32, r: f32, dur: f32, sus_level: f32) -> f32 {
    if t < a {
        (t / a).clamp(0.0, 1.0)
    } else if t < a + d {
        1.0 - ((t - a) / d).clamp(0.0, 1.0) * (1.0 - sus_level)
    } else if t < dur - r {
        sus_level * s
    } else if t < dur {
        sus_level * s * ((dur - t) / r).clamp(0.0, 1.0)
    } else {
        0.0
    }
}

// cheap deterministic noise via LCG hash
#[inline]
fn hash_noise(i: usize, seed: u32) -> f32 {
    let h = i.wrapping_mul(1103515245).wrapping_add(seed as usize) >> 16 & 0x7FFF;
    h as f32 / 16383.5 * 2.0 - 1.0
}

// ---------------------------------------------------------------------------
// Synth helpers (loop / clamp / wav_bytes scaffolding)
// ---------------------------------------------------------------------------

#[inline]
fn sine(freq: f32, t: f32) -> f32 {
    (std::f32::consts::TAU * freq * t).sin()
}

fn decay(t: f32, rate: f32) -> f32 {
    (-t * rate).exp()
}

fn render(dur: f32, mut f: impl FnMut(f32, usize) -> f32) -> Vec<u8> {
    let n = (SR as f32 * dur) as usize;
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let t = i as f32 / SR as f32;
        out.push(f(t, i));
    }
    wav_bytes(&out, SR)
}

// ---------------------------------------------------------------------------
// High-quality synthesis (44.1 kHz)
// ---------------------------------------------------------------------------

fn gen_bat_light() -> Vec<u8> {
    render(0.065f32, |t, i| {
        let env = decay(t, 65.0);
        let noise = hash_noise(i, 0x1234) * 0.28 * env;
        let thump = sine(180.0, t) * decay(t, 28.0) * 0.35;
        let crack = sine(2200.0, t) * decay(t, 140.0) * 0.22;
        let body = sine(620.0, t) * decay(t, 55.0) * 0.15;
        (noise + thump + crack + body).clamp(-1.0, 1.0) * 0.88
    })
}

fn gen_bat_heavy() -> Vec<u8> {
    render(0.095f32, |t, i| {
        let env = decay(t, 42.0);
        let noise = hash_noise(i, 0x9E37) * 0.32 * env;
        let thump = sine(110.0, t) * decay(t, 18.0) * 0.52;
        let crack = sine(1650.0, t) * decay(t, 95.0) * 0.28;
        let click = sine(3400.0, t) * decay(t, 180.0) * 0.12;
        let ring = sine(720.0, t) * decay(t, 35.0) * 0.14;
        (noise + thump + crack + click + ring).clamp(-1.0, 1.0) * 0.92
    })
}

fn gen_bat_edge() -> Vec<u8> {
    render(0.055f32, |t, i| {
        let env = decay(t, 75.0);
        let tick = sine(2800.0, t) * env * 0.45;
        let thud = sine(260.0, t) * decay(t, 45.0) * 0.18;
        let grit = hash_noise(i, 0x777) * 0.18 * env;
        (tick + thud + grit).clamp(-1.0, 1.0) * 0.85
    })
}

fn gen_wicket() -> Vec<u8> {
    let dur = 0.78f32;
    let n = (SR as f32 * dur) as usize;
    let mut out = vec![0.0f32; n];
    // three woody knocks with different resonant frequencies
    let knocks = [
        (0.00f32, 540.0, 0.62),
        (0.11, 780.0, 0.58),
        (0.24, 460.0, 0.50),
    ];
    for &(off, freq, amp) in &knocks {
        for (i, sample) in out.iter_mut().enumerate() {
            let t = i as f32 / SR as f32 - off;
            if !(0.0..0.22).contains(&t) {
                continue;
            }
            let env = decay(t, 22.0);
            let tone = sine(freq, t) * env * amp;
            let harm = sine(freq * 1.52, t) * env * amp * 0.22;
            let click = if t < 0.005 {
                (1.0 - t / 0.005) * 0.45
            } else {
                0.0
            };
            *sample = (*sample + tone + harm + click).clamp(-1.0, 1.0);
        }
    }
    // add subtle rattle tail
    for (i, sample) in out.iter_mut().enumerate() {
        let t = i as f32 / SR as f32;
        if t > 0.38 && t < 0.72 {
            let r = hash_noise(i, 0xABCD) * 0.06 * (-(t - 0.38) * 8.0).exp();
            *sample = (*sample + r).clamp(-1.0, 1.0);
        }
    }
    for s in &mut out {
        *s *= 0.88;
    }
    wav_bytes(&out, SR)
}

fn gen_catch() -> Vec<u8> {
    render(0.42f32, |t, i| {
        let env = decay(t, 18.0);
        let thud = sine(95.0, t) * env * 0.45;
        let slap = hash_noise(i, 0xC0FFEE) * 0.12 * decay(t, 55.0);
        let leather = sine(420.0, t) * decay(t, 30.0) * 0.18;
        (thud + slap + leather).clamp(-1.0, 1.0) * 0.90
    })
}

fn gen_bounce() -> Vec<u8> {
    render(0.18f32, |t, i| {
        let env = decay(t, 26.0);
        let thump = sine(90.0, t) * env * 0.55;
        let grit = hash_noise(i, 0xBEEF) * 0.10 * decay(t, 70.0);
        let wood = sine(180.0, t) * decay(t, 40.0) * 0.18;
        (thump + grit + wood).clamp(-1.0, 1.0) * 0.82
    })
}

fn gen_cheer_four() -> Vec<u8> {
    let dur = 0.95f32;
    let mut buf = [0.0f32; 6];
    let mut bi = 0;
    render(dur, |t, i| {
        let env = if t < 0.10 {
            t / 0.10
        } else if t > dur - 0.25 {
            ((dur - t) / 0.25).max(0.0)
        } else {
            1.0
        };
        let white = hash_noise(i, 0x4444);
        buf[bi] = white;
        bi = (bi + 1) % 6;
        let avg = buf.iter().sum::<f32>() / 6.0; // gentle low-pass
        // slightly bright
        let swell = 0.90 + 0.10 * (t * 4.0).sin().abs();
        let wobble = (t * 2.6).sin() * 0.06 + 1.0;
        avg * env * swell * wobble * 0.62
    })
}

fn gen_cheer_six() -> Vec<u8> {
    let dur = 2.10f32;
    let mut buf = [0.0f32; 8];
    let mut bi = 0;
    render(dur, |t, i| {
        let env = if t < 0.14 {
            t / 0.14
        } else if t > dur - 0.35 {
            ((dur - t) / 0.35).max(0.0)
        } else {
            1.0
        };
        // rising swell
        let rise = (t * 0.9).min(1.0) * 0.3 + 0.70 + 0.12 * (t * 2.0).sin().abs();
        let white = hash_noise(i, 0x5555);
        buf[bi] = white;
        bi = (bi + 1) % 8;
        let avg = buf.iter().sum::<f32>() / 8.0;
        let wobble = (t * 1.8).sin() * 0.09 + 1.0;
        // add subtle horn-like overtone sweep 180->260 Hz
        let horn_freq = 180.0 + t * 38.0;
        let horn = sine(horn_freq, t) * env * rise * 0.08 * (t * 1.2).min(1.0);
        (avg * env * rise * wobble * 0.58 + horn).clamp(-1.0, 1.0)
    })
}

fn gen_ambient() -> Vec<u8> {
    let dur = 8.0f32;
    let mut b = 0.0f32;
    render(dur, |t, i| {
        let white = hash_noise(i, 0x9999);
        b += white * 0.015;
        b = (b * 0.987).clamp(-1.0, 1.0);
        let fade = (t / 0.5).min(1.0) * ((dur - t) / 0.5).min(1.0);
        // add occasional distant shout (every ~2.5s)
        let shout_phase = (t * 0.4).sin() * 0.5 + 0.5;
        let shout = if shout_phase > 0.92 {
            hash_noise(i, 0x1111) * 0.08 * fade
        } else {
            0.0
        };
        (b * 0.13 + shout) * fade
    })
}

fn gen_ui_fallback() -> Vec<u8> {
    let dur = 0.08f32;
    render(dur, |t, _| {
        let env = if t < 0.012 {
            t / 0.012
        } else {
            ((dur - t) / 0.02).clamp(0.0, 1.0)
        };
        sine(780.0, t) * env * 0.40
    })
}

// Procedural menu music: 32s loop, 96 BPM, C-G-Am-F
fn gen_menu_music() -> Vec<u8> {
    let dur = 32.0f32;
    // Chord roots (Hz): C3, G3, A3, F3 and their major/minor triads
    let chords: [[f32; 3]; 4] = [
        [130.81, 164.81, 196.00], // C (C-E-G)
        [98.00, 123.47, 146.83],  // G (G-B-D) approx
        [110.00, 130.81, 164.81], // Am (A-C-E)
        [87.31, 110.00, 130.81],  // F (F-A-C) shifted
    ];
    let chord_dur = 8.0f32; // each chord 8s => 32s total (very slow pavilion feel)
    render(dur, |t, i| {
        let chord_idx = ((t / chord_dur) as usize) % chords.len();
        let chord = chords[chord_idx];
        let ct = t % chord_dur;
        let chord_env = (ct / 0.6).min(1.0) * ((chord_dur - ct) / 0.6).min(1.0) * 0.85 + 0.15;
        // pad: sum of chord tones as soft sines + gentle triangle via harmonic
        let mut pad = 0.0f32;
        for &f in &chord {
            pad += sine(f, t) * 0.18;
            pad += sine(f * 2.0, t) * 0.07; // octave harmonic
            pad += sine(f * 0.5, t) * 0.10; // bass octave
        }
        pad *= chord_env * 0.55;
        // subtle bass sine on root
        let bass = sine(chords[chord_idx][0] * 0.5, t) * 0.22 * chord_env;
        // soft kick every 0.625s (96 BPM)
        let beat = 60.0 / 96.0;
        let beat_phase = t % beat;
        let kick_env = decay(beat_phase, 28.0);
        let kick =
            sine(55.0, beat_phase) * kick_env * 0.18 * if beat_phase < 0.08 { 1.0 } else { 0.0 };
        let hi = if beat_phase < 0.02 {
            hash_noise(i, 0x2222) * 0.06 * decay(beat_phase, 120.0)
        } else {
            0.0
        };
        // gentle moving filter: tremolo 0.3 Hz
        let trem = 0.88 + 0.12 * (t * 0.6 * std::f32::consts::TAU).sin();
        let sample = (pad * 0.9 + bass * 0.5 + kick + hi) * trem * 0.28;
        // master fade for loopability
        let fade = (t / 0.8).min(1.0) * ((dur - t) / 0.8).min(1.0);
        (sample * fade).clamp(-1.0, 1.0)
    })
}

fn gen_match_music() -> Vec<u8> {
    // Shorter, tenser drone for in-match tension (12s loop) — low volume bed
    let dur = 12.0f32;
    render(dur, |t, i| {
        let drone = sine(55.0, t) * 0.18 + sine(110.0, t) * 0.08 + sine(82.41, t) * 0.07;
        let swell = 0.80 + 0.20 * (t * 0.35).sin();
        let noise = hash_noise(i, 0x3333) * 0.015;
        let fade = (t / 0.6).min(1.0) * ((dur - t) / 0.6).min(1.0);
        ((drone * swell + noise) * 0.18 * fade).clamp(-1.0, 1.0)
    })
}

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

pub struct AudioPlugin;

impl Plugin for AudioPlugin {
    fn build(&self, app: &mut App) {
        // Embed Kenney CC0 UI sounds (keep binary self-contained)
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/confirm.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/back.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/nav.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/tick.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/error.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/bong.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/click1.ogg");
        bevy::asset::embedded_asset!(app, "../../assets/audio/ui/rollover.ogg");

        app.init_resource::<AudioSettings>()
            .init_resource::<CommentaryHandles>()
            .init_resource::<CommentaryHistory>()
            .init_resource::<CommentaryPlaying>()
            .init_resource::<CommentaryScheduler>()
            .init_resource::<CommentaryDurations>()
            .init_resource::<CommentaryResultPauseEdge>()
            .add_systems(Startup, setup_audio)
            .add_systems(Startup, setup_commentary.after(setup_audio))
            .add_systems(
                OnEnter(crate::state::AppState::InMatch),
                commentary_on_match_enter,
            )
            .add_systems(
                Update,
                (
                    bat_crack_on_hit,
                    bounce_sfx,
                    sfx_on_result,
                    ui_feedback,
                    ambient_control,
                    music_control,
                    apply_volumes,
                    (commentary_on_result, commentary_on_phase, commentary_update).chain(),
                ),
            );
    }
}

fn setup_audio(
    mut commands: Commands,
    mut assets: ResMut<Assets<AudioSource>>,
    asset_server: Res<AssetServer>,
    mut global_vol: ResMut<GlobalVolume>,
) {
    // Procedural SFX
    let h_bat_light = assets.add(AudioSource {
        bytes: gen_bat_light().into(),
    });
    let h_bat_heavy = assets.add(AudioSource {
        bytes: gen_bat_heavy().into(),
    });
    let h_bat_edge = assets.add(AudioSource {
        bytes: gen_bat_edge().into(),
    });
    let h_wicket = assets.add(AudioSource {
        bytes: gen_wicket().into(),
    });
    let h_catch = assets.add(AudioSource {
        bytes: gen_catch().into(),
    });
    let h_bounce = assets.add(AudioSource {
        bytes: gen_bounce().into(),
    });
    let h_four = assets.add(AudioSource {
        bytes: gen_cheer_four().into(),
    });
    let h_six = assets.add(AudioSource {
        bytes: gen_cheer_six().into(),
    });
    let h_ambient = assets.add(AudioSource {
        bytes: gen_ambient().into(),
    });
    let h_fallback = assets.add(AudioSource {
        bytes: gen_ui_fallback().into(),
    });

    let h_menu = assets.add(AudioSource {
        bytes: gen_menu_music().into(),
    });
    let h_match = assets.add(AudioSource {
        bytes: gen_match_music().into(),
    });

    commands.insert_resource(SfxHandles {
        bat_light: h_bat_light,
        bat_heavy: h_bat_heavy,
        bat_edge: h_bat_edge,
        wicket: h_wicket,
        catch: h_catch,
        bounce: h_bounce,
        cheer_four: h_four,
        cheer_six: h_six,
        ambient: h_ambient.clone(),
        ui_fallback: h_fallback,
    });
    commands.insert_resource(MusicHandles {
        menu: h_menu.clone(),
        match_loop: h_match.clone(),
    });

    // CC0 UI OGG handles — load from assets/ (works both with filesystem and embedded)
    // Files are also embedded via embedded_asset! above for self-contained release builds.
    let ui = UiHandles {
        confirm: asset_server.load("audio/ui/confirm.ogg"),
        back: asset_server.load("audio/ui/back.ogg"),
        nav: asset_server.load("audio/ui/nav.ogg"),
        tick: asset_server.load("audio/ui/tick.ogg"),
        error: asset_server.load("audio/ui/error.ogg"),
        bong: asset_server.load("audio/ui/bong.ogg"),
    };
    commands.insert_resource(ui);

    global_vol.volume = Volume::Linear(0.85);

    // Ambient crowd murmur (always looping, volume ducked per state)
    commands.spawn((
        AmbientTag,
        AudioPlayer(h_ambient),
        PlaybackSettings {
            mode: bevy::audio::PlaybackMode::Loop,
            volume: Volume::Linear(0.14),
            ..default()
        },
    ));
    // Menu music loop
    commands.spawn((
        MusicMenuTag,
        AudioPlayer(h_menu),
        PlaybackSettings {
            mode: bevy::audio::PlaybackMode::Loop,
            volume: Volume::Linear(0.22),
            ..default()
        },
    ));
    // Match ambient music loop (tenser, very low)
    commands.spawn((
        MusicMatchTag,
        AudioPlayer(h_match),
        PlaybackSettings {
            mode: bevy::audio::PlaybackMode::Loop,
            volume: Volume::Linear(0.0),
            ..default()
        },
    ));
}

const COMMENTARY_DURATIONS_JSON: &str =
    include_str!("../../assets/audio/commentary/durations.json");

fn setup_commentary(
    _commands: Commands,
    asset_server: Res<AssetServer>,
    mut handles: ResMut<CommentaryHandles>,
    mut durations: ResMut<CommentaryDurations>,
) {
    // Category counts must match scripts/generate_commentary_fixed.py LIBRARY.
    let cats: &[(&str, usize)] = &[
        ("welcome", 2),
        ("dot", 5),
        ("single", 4),
        ("two", 2),
        ("three", 1),
        ("four", 5),
        ("six", 4),
        ("wide", 2),
        ("bowled", 3),
        ("caught", 3),
        ("caught_behind", 2),
        ("run_out", 2),
        ("over_complete", 3),
        ("innings_break", 2),
        ("match_win", 2),
        ("match_tie", 1),
        ("beaten", 3),
        // Analyst fact lines — each category is ONE exact fact; a variant may
        // only exist if it states the same fact.
        ("context_fifty", 1),         // striker reaches fifty
        ("context_century", 1),       // batter reaches hundred
        ("context_team_hundred", 1),  // team total crosses hundred
        ("context_rrr", 1),           // required rate climbing above 11
        ("context_dots", 1),          // three consecutive dot balls
        ("context_clutch_wicket", 1), // wicket while chase is tense
        ("context_bowler", 2),        // excellent spell at over end
    ];
    for role in ["male", "female"] {
        for (cat, count) in cats {
            let mut vec = Vec::new();
            for i in 1..=*count {
                let path = format!("audio/commentary/{}/{}_{:02}.ogg", role, cat, i);
                let h: Handle<AudioSource> = asset_server.load(path);
                vec.push(h);
            }
            if role == "male" {
                handles.male.insert(cat.to_string(), vec);
            } else {
                handles.female.insert(cat.to_string(), vec);
            }
        }
    }
    // Real durations for scheduling (editorial validation: reject bad entries).
    if let Ok(map) = serde_json::from_str::<HashMap<String, f32>>(COMMENTARY_DURATIONS_JSON) {
        let good: HashMap<String, f32> = map
            .into_iter()
            .filter(|(_, d)| *d >= 0.8 && *d <= 6.5)
            .collect();
        info!(
            "Commentary loaded: male {} cats, female {} cats, {} validated durations",
            handles.male.len(),
            handles.female.len(),
            good.len()
        );
        durations.0 = good;
    }
}

/// Which role speaks a category. Analyst handles all contextual lines so the
/// partnership feels like lead calls the action, analyst supplies analysis.
fn role_for_category(settings_voice: CommentaryVoice, category: &str) -> &'static str {
    let lead_male = settings_voice != CommentaryVoice::Female;
    let is_analyst_line = category.starts_with("context_");
    match (lead_male, is_analyst_line) {
        // Male lead -> female analyst speaks context
        (true, true) => "female",
        // Female lead -> male analyst speaks context
        (false, true) => "male",
        // Lead speaks everything else
        (true, false) => "male",
        (false, false) => "female",
    }
}

/// Routine events are gated probabilistically and by cooldown so commentary
/// breathes; key moments always get called.
fn is_routine(category: &str) -> bool {
    matches!(category, "dot" | "beaten" | "single" | "two" | "three")
}

/// Probability that we bother calling this routine event at all.
fn routine_call_chance(category: &str) -> f32 {
    match category {
        "dot" => 0.30,
        "beaten" => 0.45,
        "single" => 0.50,
        "two" => 0.65,
        "three" => 0.85,
        _ => 1.0,
    }
}

/// Set a queued analyst follow-up only if nothing is queued yet.
fn set_queued(playing: &mut CommentaryPlaying, category: &str, delay: f32) {
    if playing.queued.is_none() {
        playing.queued = Some((category.to_string(), delay));
    }
}

// ---------------------------------------------------------------------------
// Commentary resource grouping
// ---------------------------------------------------------------------------

/// Borrow bundle for commentary helper functions.
struct CommentaryCtx<'a> {
    handles: &'a CommentaryHandles,
    durations: &'a CommentaryDurations,
    history: &'a mut CommentaryHistory,
    playing: &'a mut CommentaryPlaying,
    scheduler: &'a mut CommentaryScheduler,
    settings: &'a AudioSettings,
}

#[derive(SystemParam)]
struct CommentaryParam<'w> {
    handles: Option<Res<'w, CommentaryHandles>>,
    durations: Option<Res<'w, CommentaryDurations>>,
    history: ResMut<'w, CommentaryHistory>,
    playing: ResMut<'w, CommentaryPlaying>,
    scheduler: ResMut<'w, CommentaryScheduler>,
    settings: Res<'w, AudioSettings>,
}

impl<'w> CommentaryParam<'w> {
    fn ctx_mut(&mut self) -> Option<CommentaryCtx<'_>> {
        let handles = self.handles.as_deref()?;
        let durations = self.durations.as_deref()?;
        Some(CommentaryCtx {
            handles,
            durations,
            history: &mut self.history,
            playing: &mut self.playing,
            scheduler: &mut self.scheduler,
            settings: &self.settings,
        })
    }
}

/// Map result banner text (uppercased) to a commentary category.
/// Order and precedence are significant; `None` means silence (wide or unknown).
fn result_commentary_category(upper: &str) -> Option<&'static str> {
    const RULES: &[(&[&str], Option<&'static str>)] = &[
        (&["SIX", "MAXIMUM"], Some("six")),
        (&["FOUR"], Some("four")),
        (&["BOWLED"], Some("bowled")),
        (&["TAKEN BEHIND"], Some("caught_behind")),
        (&["CAUGHT", "TAKEN"], Some("caught")),
        (&["RUN OUT"], Some("run_out")),
        (&["WIDE"], None), // wides stay uncalled most of the time (restraint)
        (&["BEATEN", "PAST THE EDGE"], Some("beaten")),
        (&["COME BACK FOR THREE"], Some("three")),
        (
            &[
                "BACK FOR THE SECOND",
                "COME BACK FOR 2",
                "COME BACK FOR TWO",
            ],
            Some("two"),
        ),
        (&["QUICK SINGLE", "SINGLE TAKEN"], Some("single")),
        (&["SHOULDERED ARMS", "DOT BALL", "FIELDED"], Some("dot")),
    ];
    for (patterns, category) in RULES {
        if patterns.iter().any(|p| upper.contains(p)) {
            return *category;
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Commentary lifecycle & scheduling (pure helpers — unit-tested)
// ---------------------------------------------------------------------------

/// Reset match-scoped commentary history at every match-session boundary
/// (`AppState::InMatch` entry). Fingerprint records teams/overs for debugging
/// only — identical rematch setups still get a fresh lifecycle.
pub fn reset_commentary_history_for_match_session(
    history: &mut CommentaryHistory,
    teams: [usize; 2],
    overs: u32,
) {
    history.last_category.clear();
    history.last_indices.clear();
    history.lifecycle = CommentaryLifecycle {
        match_fp: Some(MatchFingerprint { teams, overs }),
        match_intro_pending: true,
        intro_open: true,
        ..CommentaryLifecycle::default()
    };
    history.striker_runs = 0;
    history.team_runs = 0;
    history.rrr_last = None;
    history.consecutive_dots = 0;
    history.over_start_runs = 0;
    history.over_start_valid = false;
    history.routine_cooldown = 0.0;
}

/// True on the first frame of each `ResultPause` occurrence (not on held frames).
pub fn result_pause_entered(prev_in_result_pause: bool, in_result_pause: bool) -> bool {
    in_result_pause && !prev_in_result_pause
}

/// Seconds the opening walk-on should run, derived from the welcome clip table.
pub fn welcome_intro_duration_secs(voice: CommentaryVoice, durations: &CommentaryDurations) -> f32 {
    const MIN: f32 = 2.0;
    const MAX: f32 = 5.0;
    const FALLBACK: f32 = 2.6;
    const TAIL: f32 = 0.35;

    if voice == CommentaryVoice::Off {
        return FALLBACK.clamp(MIN, MAX);
    }
    let role = if voice == CommentaryVoice::Female {
        "female"
    } else {
        "male"
    };
    let prefix = format!("{role}/welcome_");
    let clip = durations
        .0
        .iter()
        .filter(|(k, _)| k.starts_with(&prefix))
        .map(|(_, d)| *d)
        .fold(0.0_f32, f32::max);
    let base = if clip > 0.0 { clip } else { FALLBACK };
    (base + TAIL).clamp(MIN, MAX)
}

/// Welcome plays exactly once at true match start — never on recurring ReadyToBall.
pub fn should_play_welcome(
    lc: &CommentaryLifecycle,
    innings_num: u8,
    legal_balls: u32,
    runs: u32,
) -> bool {
    !lc.welcome_played
        && innings_num == 1
        && legal_balls == 0
        && runs == 0
        && lc.deliveries_completed == 0
}

/// Consume `match_intro_pending` when match facts are pristine; abandon if play has begun.
pub fn consume_match_intro_pending(
    lc: &mut CommentaryLifecycle,
    innings_num: u8,
    legal_balls: u32,
    runs: u32,
) -> bool {
    if !lc.match_intro_pending {
        return false;
    }
    if lc.deliveries_completed > 0 {
        lc.match_intro_pending = false;
        return false;
    }
    if !should_play_welcome(lc, innings_num, legal_balls, runs) {
        return false;
    }
    lc.match_intro_pending = false;
    lc.welcome_played = true;
    true
}

pub fn priority_for_category(category: &str) -> CommentaryPriority {
    match category {
        "welcome" => CommentaryPriority::Welcome,
        "over_complete" | "innings_break" | "match_win" | "match_tie" => CommentaryPriority::Phase,
        _ => CommentaryPriority::Result,
    }
}

/// Whether an incoming request may replace a pending one (lower priority value wins).
pub fn scheduler_should_accept(
    pending: Option<CommentaryPriority>,
    incoming: CommentaryPriority,
) -> bool {
    match pending {
        None => true,
        Some(cur) => incoming <= cur,
    }
}

fn schedule_commentary(
    scheduler: &mut CommentaryScheduler,
    category: &str,
    variant: Option<usize>,
    priority: CommentaryPriority,
) {
    let accept = scheduler_should_accept(scheduler.pending.as_ref().map(|p| p.priority), priority);
    if accept {
        scheduler.pending = Some(ScheduledCommentary {
            category: category.to_string(),
            variant,
            priority,
        });
    }
}

fn dispatch_pending_commentary(commands: &mut Commands, ctx: &mut CommentaryCtx<'_>) -> f32 {
    if ctx.playing.remaining > 0.25 {
        return 0.0;
    }
    let Some(call) = ctx.scheduler.pending.take() else {
        return 0.0;
    };
    play_commentary(commands, ctx, &call.category, call.variant)
}

/// Request a lead commentary call: plays immediately when the slot is free,
/// otherwise queues by priority (result lines cannot be displaced).
fn request_commentary(
    commands: &mut Commands,
    ctx: &mut CommentaryCtx<'_>,
    category: &str,
    variant: Option<usize>,
    priority: CommentaryPriority,
) -> f32 {
    if ctx.history.lifecycle.intro_open && category != "welcome" {
        return 0.0;
    }
    if ctx.playing.remaining > 0.25 {
        info!(
            "Commentary requested: {category} (priority {:?}, queued — slot busy)",
            priority
        );
        schedule_commentary(ctx.scheduler, category, variant, priority);
        return 0.0;
    }
    // Slot is free — drop any lower-priority pending call and play now.
    if let Some(pending) = &ctx.scheduler.pending
        && priority <= pending.priority
    {
        ctx.scheduler.pending = None;
    }
    info!(
        "Commentary requested: {category} (priority {:?}, playing now)",
        priority
    );
    play_commentary(commands, ctx, category, variant)
}

/// Play a commentary clip. `variant = None` picks a random variant (all
/// variants of a category state the same fact); `Some(n)` plays an exact
/// clip, required when variants encode different facts.
fn play_commentary(
    commands: &mut Commands,
    ctx: &mut CommentaryCtx<'_>,
    category: &str,
    variant: Option<usize>,
) -> f32 {
    if ctx.settings.commentary == CommentaryVoice::Off {
        return 0.0;
    }
    if ctx.history.lifecycle.intro_open && category != "welcome" {
        return 0.0;
    }
    if ctx.playing.remaining > 0.25 {
        return 0.0; // never overlap
    }
    let role = role_for_category(ctx.settings.commentary, category);
    let map = if role == "male" {
        &ctx.handles.male
    } else {
        &ctx.handles.female
    };
    let Some(list) = map.get(category) else {
        return 0.0;
    };
    if list.is_empty() {
        return 0.0;
    }
    // Variant selection: exact when given; otherwise random avoiding repeat.
    let idx = match variant {
        Some(n) => n.min(list.len() - 1),
        None => {
            let last_idx = ctx
                .history
                .last_indices
                .get(category)
                .copied()
                .unwrap_or(usize::MAX);
            let mut i = (rand::random::<u32>() as usize) % list.len();
            if list.len() > 1 && i == last_idx {
                i = (i + 1) % list.len();
            }
            ctx.history.last_indices.insert(category.to_string(), i);
            i
        }
    };
    ctx.history.last_category = category.to_string();

    let handle = list[idx].clone();
    let vol = (ctx.settings.master * ctx.settings.commentary_volume * 1.05).clamp(0.0, 1.0);
    commands.spawn((
        AudioPlayer(handle),
        PlaybackSettings {
            mode: bevy::audio::PlaybackMode::Despawn,
            volume: Volume::Linear(vol),
            speed: 1.0,
            ..default()
        },
    ));
    // Real duration from generated manifest; fall back to a safe estimate.
    let file_key = format!("{role}/{category}_{:02}.ogg", idx + 1);
    let dur = ctx.durations.0.get(&file_key).copied().unwrap_or(2.5) + 0.15; // small tail before next clip may start
    ctx.playing.remaining = dur;
    info!(
        "Commentary playing: {category} variant {:02} role {role} ({:.2}s)",
        idx + 1,
        dur
    );
    dur
}

fn try_dispatch_match_intro(
    commands: &mut Commands,
    ctx: &mut CommentaryCtx<'_>,
    m: &crate::game::ActiveMatch,
) {
    if !consume_match_intro_pending(
        &mut ctx.history.lifecycle,
        m.state.innings_num,
        m.state.innings.legal_balls,
        m.state.innings.runs,
    ) {
        return;
    }
    request_commentary(commands, ctx, "welcome", None, CommentaryPriority::Welcome);
}

fn commentary_on_match_enter(
    mut history: ResMut<CommentaryHistory>,
    mut playing: ResMut<CommentaryPlaying>,
    mut scheduler: ResMut<CommentaryScheduler>,
    mut result_edge: ResMut<CommentaryResultPauseEdge>,
    setup: Res<crate::game::MatchSetup>,
) {
    reset_commentary_history_for_match_session(&mut history, setup.teams, setup.overs);
    scheduler.pending = None;
    playing.queued = None;
    result_edge.in_result_pause = false;
}

fn commentary_update(
    mut commands: Commands,
    time: Res<Time>,
    state: Res<State<crate::state::AppState>>,
    am: Option<Res<crate::game::ActiveMatch>>,
    mut commentary: CommentaryParam,
) {
    if commentary.history.routine_cooldown > 0.0 {
        commentary.history.routine_cooldown -= time.delta_secs();
    }
    let was_active = commentary.playing.remaining > 0.0;
    if commentary.playing.remaining > 0.0 {
        commentary.playing.remaining -= time.delta_secs();
        if commentary.playing.remaining < 0.0 {
            commentary.playing.remaining = 0.0;
        }
    }
    if *state.get() == crate::state::AppState::InMatch {
        if let (Some(mut ctx), Some(m)) = (commentary.ctx_mut(), am.as_deref()) {
            try_dispatch_match_intro(&mut commands, &mut ctx, m);
        }
    }
    if commentary.history.lifecycle.intro_open
        && commentary.history.lifecycle.welcome_played
        && commentary.playing.remaining <= 0.0
    {
        commentary.history.lifecycle.intro_open = false;
    }
    // Dispatch any priority-queued lead call once the slot opens.
    if let Some(mut ctx) = commentary.ctx_mut() {
        dispatch_pending_commentary(&mut commands, &mut ctx);
    }
    // Fire queued analyst follow-up once the lead call has finished.
    let queued = commentary.playing.queued.clone();
    if let Some((cat, delay)) = queued {
        if delay <= 0.0 {
            commentary.playing.queued = None;
            if let Some(mut ctx) = commentary.ctx_mut() {
                play_commentary(&mut commands, &mut ctx, &cat, None);
            }
        } else {
            commentary.playing.queued = Some((cat, delay - time.delta_secs()));
        }
    }
    // Smooth side-chain ducking: fast attack (~0.25 s), slow release (~2 s).
    let target_duck = if commentary.playing.remaining > 0.0 {
        0.30
    } else {
        1.0
    };
    let rate = if target_duck < commentary.playing.duck_level {
        (1.0 - target_duck).max(0.001) / 0.25 // attack per second
    } else {
        (1.0 - target_duck).max(0.001) / 2.0 // release per second
    };
    let step = rate * time.delta_secs();
    if commentary.playing.duck_level > target_duck {
        commentary.playing.duck_level = (commentary.playing.duck_level - step).max(target_duck);
    } else {
        commentary.playing.duck_level = (commentary.playing.duck_level + step).min(target_duck);
    }
    let _ = was_active;
}

fn commentary_on_result(
    mut commands: Commands,
    phase: Res<crate::game::Phase>,
    am: Option<Res<crate::game::ActiveMatch>>,
    _wd: Option<Res<crate::game::WorldData>>,
    mut commentary: CommentaryParam,
    mut result_edge: ResMut<CommentaryResultPauseEdge>,
) {
    if commentary.handles.is_none() || commentary.durations.is_none() {
        return;
    }
    if commentary.history.lifecycle.intro_open {
        return;
    }
    let in_result_pause = matches!(&phase.0, crate::game::PhaseEnum::ResultPause { .. });
    if !in_result_pause {
        if result_edge.in_result_pause {
            result_edge.in_result_pause = false;
            commentary.history.consecutive_dots = 0;
            commentary.history.over_start_valid = false;
        }
        return;
    }
    if !result_pause_entered(result_edge.in_result_pause, in_result_pause) {
        return;
    }
    result_edge.in_result_pause = true;
    let crate::game::PhaseEnum::ResultPause { text, .. } = &phase.0 else {
        return;
    };
    commentary.history.lifecycle.deliveries_completed += 1;
    let upper = text.to_uppercase();

    // ---- Capture facts before updating trackers (threshold crossings) ----
    let prev_striker = commentary.history.striker_runs;
    let prev_team = commentary.history.team_runs;
    let striker_runs_now = am
        .as_deref()
        .map(|m| m.state.innings.card_of(m.state.innings.striker).runs);
    let team_runs_now = am.as_deref().map(|m| m.state.innings.runs);

    // ---- Map result text to an action-call category ----
    let category = match result_commentary_category(&upper) {
        Some(c) => c,
        None => return, // wide, unknown result: silence beats guessing
    };
    match category {
        "six" | "four" | "three" | "two" | "single" => commentary.history.consecutive_dots = 0,
        "dot" => commentary.history.consecutive_dots += 1,
        _ => {}
    }

    // ---- Restraint: routine events may go uncalled (commentary gaps) ----
    let gates_pass = !is_routine(category)
        || (commentary.history.routine_cooldown <= 0.0
            && rand::random::<f32>() <= routine_call_chance(category));

    let mut lead_dur = 0.0;
    if gates_pass {
        let mut ctx = commentary
            .ctx_mut()
            .expect("handles and durations checked above");
        lead_dur = request_commentary(
            &mut commands,
            &mut ctx,
            category,
            None,
            CommentaryPriority::Result,
        );
        if is_routine(category) {
            commentary.history.routine_cooldown = 7.0;
        }
    }

    // ---- Sync tracked facts ----
    if let Some(r) = striker_runs_now {
        commentary.history.striker_runs = r;
    }
    if let Some(r) = team_runs_now {
        commentary.history.team_runs = r;
    }

    // ---- Analyst follow-ups: only exact, verified facts ----
    // Priority: century > fifty > team hundred.
    if let Some(runs) = striker_runs_now {
        if prev_striker < 100 && runs >= 100 {
            set_queued(&mut commentary.playing, "context_century", lead_dur + 0.45);
        } else if prev_striker < 50 && runs >= 50 {
            set_queued(&mut commentary.playing, "context_fifty", lead_dur + 0.45);
        }
    }
    if commentary.playing.queued.is_none()
        && let Some(runs) = team_runs_now
        && prev_team < 100
        && runs >= 100
    {
        set_queued(
            &mut commentary.playing,
            "context_team_hundred",
            lead_dur + 0.45,
        );
    }
    // Three consecutive dots.
    if commentary.history.consecutive_dots >= 3 {
        set_queued(&mut commentary.playing, "context_dots", lead_dur + 0.4);
        commentary.history.consecutive_dots = 0;
    }
    // Required rate climbing above 11 while chasing.
    if let Some(m) = am.as_deref()
        && let Some(tg) = m.state.innings.target
    {
        let need = tg.saturating_sub(m.state.innings.runs) as f32;
        let overs_left = ((m.state.overs * 6).saturating_sub(m.state.innings.legal_balls) as f32
            / 6.0)
            .max(0.34);
        let rrr = need / overs_left;
        if let Some(prev) = commentary.history.rrr_last
            && rrr > prev
            && rrr > 11.0
        {
            set_queued(&mut commentary.playing, "context_rrr", lead_dur + 0.5);
        }
        commentary.history.rrr_last = Some(rrr);
        // Wicket at a crucial moment: chasing and need is getting real.
        let is_wicket = matches!(category, "bowled" | "caught" | "caught_behind" | "run_out");
        if is_wicket && need <= 45.0 {
            set_queued(
                &mut commentary.playing,
                "context_clutch_wicket",
                lead_dur + 0.55,
            );
        }
    }
}

fn commentary_on_phase(
    mut commands: Commands,
    phase: Res<crate::game::Phase>,
    am: Option<Res<crate::game::ActiveMatch>>,
    _wd: Option<Res<crate::game::WorldData>>,
    mut commentary: CommentaryParam,
    mut last_phase: Local<String>,
) {
    let Some(mut ctx) = commentary.ctx_mut() else {
        return;
    };
    let phase_str = format!("{:?}", std::mem::discriminant(&phase.0));
    if phase_str == *last_phase {
        return;
    }
    *last_phase = phase_str;

    match &phase.0 {
        crate::game::PhaseEnum::OverBreak { .. } => {
            // Pick over-summary variant from real facts:
            // 0 = "End of the over.", 1 = "A quiet over." (<=3), 2 = "An expensive over." (>=10)
            let runs_in_over = if ctx.history.over_start_valid {
                am.as_deref().map(|m| {
                    m.state
                        .innings
                        .runs
                        .saturating_sub(ctx.history.over_start_runs)
                })
            } else {
                None
            };
            let variant = match runs_in_over {
                Some(r) if r <= 3 => 1,
                Some(r) if r >= 10 => 2,
                _ => 0,
            };
            request_commentary(
                &mut commands,
                &mut ctx,
                "over_complete",
                Some(variant),
                CommentaryPriority::Phase,
            );
            // Analyst praises an excellent spell when facts support it.
            let spell_good = am
                .as_deref()
                .and_then(|m| {
                    let b = m.state.innings.current_bowler?;
                    let card = m.state.innings.bowler_card_of(b);
                    let overs = card.balls as f32 / 6.0;
                    Some(
                        card.wickets >= 2
                            && overs >= 2.0
                            && card.runs as f32 / overs.max(1.0) < 7.0,
                    )
                })
                .unwrap_or(false);
            if spell_good {
                ctx.playing.queued = Some(("context_bowler".into(), ctx.playing.remaining + 0.4));
            }
            // Reset over bookkeeping.
            if let Some(m) = am.as_deref() {
                ctx.history.over_start_runs = m.state.innings.runs;
                ctx.history.over_start_valid = true;
            }
        }
        crate::game::PhaseEnum::InningsBreak => {
            let inns = am.as_deref().map(|m| m.state.innings_num).unwrap_or(0);
            if ctx.history.lifecycle.innings_break_played_for != inns {
                ctx.history.lifecycle.innings_break_played_for = inns;
                request_commentary(
                    &mut commands,
                    &mut ctx,
                    "innings_break",
                    None,
                    CommentaryPriority::Phase,
                );
            }
            ctx.history.over_start_valid = false;
            ctx.history.rrr_last = None;
            ctx.history.striker_runs = 0;
        }
        crate::game::PhaseEnum::MatchOver => {
            let tied = am
                .as_deref()
                .map(|m| matches!(m.state.result, Some(crate::core::rules::Result::Tie)))
                .unwrap_or(false);
            let cat = if tied { "match_tie" } else { "match_win" };
            request_commentary(
                &mut commands,
                &mut ctx,
                cat,
                None,
                CommentaryPriority::Phase,
            );
        }
        crate::game::PhaseEnum::ReadyToBall { .. } => {
            if let Some(m) = am.as_deref() {
                ctx.history.over_start_runs = m.state.innings.runs;
                ctx.history.over_start_valid = true;
            }
        }
        _ => {}
    }
}

fn apply_volumes(settings: Res<AudioSettings>, mut global: ResMut<GlobalVolume>) {
    if settings.is_changed() {
        global.volume = Volume::Linear(settings.master.clamp(0.0, 1.0));
    }
}

fn ambient_control(
    state: Res<State<crate::state::AppState>>,
    settings: Res<AudioSettings>,
    mut q: Query<&mut PlaybackSettings, With<AmbientTag>>,
) {
    let target = if *state.get() == crate::state::AppState::Menu {
        0.08
    } else {
        0.18
    } * settings.sfx;
    for mut s in &mut q {
        s.volume = Volume::Linear(target);
    }
}

fn music_control(
    state: Res<State<crate::state::AppState>>,
    settings: Res<AudioSettings>,
    playing: Res<CommentaryPlaying>,
    mut menu_q: Query<&mut PlaybackSettings, (With<MusicMenuTag>, Without<MusicMatchTag>)>,
    mut match_q: Query<&mut PlaybackSettings, (With<MusicMatchTag>, Without<MusicMenuTag>)>,
) {
    let is_menu = *state.get() == crate::state::AppState::Menu;
    let mvol = settings.music.clamp(0.0, 1.0);
    let duck = if playing.remaining > 0.1 { 0.35 } else { 1.0 };
    for mut s in &mut menu_q {
        let target = if is_menu { 0.26 * duck } else { 0.0 } * mvol;
        s.volume = Volume::Linear(target);
    }
    for mut s in &mut match_q {
        // In-match background music: stadium bed, more audible than before (0.12) and ducks when commentary
        let base = if is_menu { 0.0 } else { 0.14 };
        let target = base * duck * mvol;
        s.volume = Volume::Linear(target);
    }
}

fn play_once(commands: &mut Commands, handle: Handle<AudioSource>, vol: f32, pitch: f32) {
    commands.spawn((
        AudioPlayer(handle),
        PlaybackSettings {
            mode: bevy::audio::PlaybackMode::Despawn,
            volume: Volume::Linear(vol.clamp(0.0, 1.0)),
            speed: pitch,
            ..default()
        },
    ));
}

// Tiered bat crack the instant the ball is struck
fn bat_crack_on_hit(
    mut commands: Commands,
    ball_q: Query<&crate::game::ball::BallState>,
    attempt: Res<crate::game::ShotAttempt>,
    handles: Option<Res<SfxHandles>>,
    settings: Res<AudioSettings>,
    mut was_struck: Local<bool>,
) {
    let Some(h) = handles else { return };
    let Ok(bs) = ball_q.single() else { return };
    let now_struck = bs.struck && !bs.dead;
    if now_struck && !*was_struck {
        // Determine tier from timing offset
        let tier_heavy = if let Some(off) = attempt.offset {
            off.abs() < 0.07
        } else {
            bs.vel.length() > 28.0
        };
        let is_edge = if let Some(off) = attempt.offset {
            off.abs() >= 0.19
        } else {
            false
        };
        let (handle, pitch, vol) = if is_edge {
            (h.bat_edge.clone(), 1.0, settings.sfx * 0.85)
        } else if tier_heavy {
            let p = 0.94 + (bs.vel.length() / 45.0).clamp(0.0, 0.18);
            (h.bat_heavy.clone(), p, settings.sfx)
        } else {
            let p = 0.98 + (bs.vel.length() / 50.0).clamp(0.0, 0.14);
            (h.bat_light.clone(), p, settings.sfx * 0.92)
        };
        play_once(&mut commands, handle, vol * 0.95, pitch);
    }
    *was_struck = now_struck;
}

// Pitch bounce thud (first bounce before being struck)
fn bounce_sfx(
    mut commands: Commands,
    mut ball_q: Query<(&crate::game::ball::BallState, &crate::game::ball::BallFlags)>,
    handles: Option<Res<SfxHandles>>,
    settings: Res<AudioSettings>,
) {
    let Some(h) = handles else { return };
    let Ok((bs, flags)) = ball_q.single_mut() else {
        return;
    };
    if flags.just_bounced && !bs.struck && !bs.dead {
        // softer bounce, slight pitch variation by speed
        let v = bs.vel.length() / 25.0;
        let pitch = (0.92 + v * 0.12).clamp(0.85, 1.15);
        play_once(&mut commands, h.bounce.clone(), settings.sfx * 0.45, pitch);
    }
}

// Crowd + wicket/catch/four/six when result banner appears
fn sfx_on_result(
    mut commands: Commands,
    phase: Res<crate::game::Phase>,
    handles: Option<Res<SfxHandles>>,
    settings: Res<AudioSettings>,
    mut last_text: Local<String>,
) {
    let Some(h) = handles else { return };
    let crate::game::PhaseEnum::ResultPause { text, .. } = &phase.0 else {
        if !last_text.is_empty() {
            *last_text = String::new();
        }
        return;
    };
    if text == &*last_text {
        return;
    }
    *last_text = text.clone();
    let upper = text.to_uppercase();

    if upper.contains("BOWLED") || upper.contains("RUN OUT") {
        play_once(&mut commands, h.wicket.clone(), settings.sfx, 1.0);
        // add a short cheer tail 0.25s later via second cheer
        play_once(
            &mut commands,
            h.cheer_four.clone(),
            settings.sfx * 0.55,
            1.05,
        );
    } else if upper.contains("CAUGHT") || upper.contains("TAKEN") {
        play_once(&mut commands, h.catch.clone(), settings.sfx * 0.85, 1.0);
        play_once(&mut commands, h.wicket.clone(), settings.sfx * 0.35, 1.1);
        play_once(&mut commands, h.cheer_four.clone(), settings.sfx * 0.6, 1.0);
    } else if upper.contains("SIX") || upper.contains("MAXIMUM") {
        play_once(&mut commands, h.cheer_six.clone(), settings.sfx, 1.0);
    } else if upper.contains("FOUR") {
        play_once(&mut commands, h.cheer_four.clone(), settings.sfx, 1.02);
    } else if upper.contains("WIDE") {
        play_once(
            &mut commands,
            h.ui_fallback.clone(),
            settings.sfx * 0.45,
            1.25,
        );
    } else if upper.contains("BEATEN") || upper.contains("EDGE") {
        // edge already had bat_edge; add subtle gasp via short cheer
        play_once(
            &mut commands,
            h.cheer_four.clone(),
            settings.sfx * 0.25,
            1.15,
        );
    }
}

// Menu UI feedback with distinct Kenney sounds
fn ui_feedback(
    mut commands: Commands,
    input: Res<crate::input::PlayerInput>,
    handles: Option<Res<UiHandles>>,
    fallback: Option<Res<SfxHandles>>,
    settings: Res<AudioSettings>,
    state: Res<State<crate::state::AppState>>,
) {
    if *state.get() != crate::state::AppState::Menu {
        return;
    }
    let sfx = settings.sfx;
    // Prefer embedded CC0 handles, fall back to procedural
    let (h_confirm, h_back, h_nav) = if let Some(ui) = handles.as_deref() {
        (ui.confirm.clone(), ui.back.clone(), ui.nav.clone())
    } else if let Some(fb) = fallback.as_deref() {
        (
            fb.ui_fallback.clone(),
            fb.ui_fallback.clone(),
            fb.ui_fallback.clone(),
        )
    } else {
        return;
    };

    if input.pressed(crate::input::Action::Confirm) {
        play_once(&mut commands, h_confirm, sfx * 0.70, 1.0);
    } else if input.pressed(crate::input::Action::Cancel) {
        play_once(&mut commands, h_back, sfx * 0.65, 1.0);
    } else if input.pressed(crate::input::Action::Next) || input.pressed(crate::input::Action::Prev)
    {
        // slight pitch variation to avoid monotony
        let pitch = if input.pressed(crate::input::Action::Next) {
            1.0
        } else {
            0.96
        };
        play_once(&mut commands, h_nav, sfx * 0.45, pitch);
    } else if input.pressed(crate::input::Action::Left)
        || input.pressed(crate::input::Action::Right)
    {
        // slider adjust tick
        let pitch = if input.pressed(crate::input::Action::Right) {
            1.08
        } else {
            0.92
        };
        play_once(&mut commands, h_nav, sfx * 0.35, pitch);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fresh_lifecycle() -> CommentaryLifecycle {
        CommentaryLifecycle {
            match_fp: Some(MatchFingerprint {
                teams: [0, 1],
                overs: 20,
            }),
            ..Default::default()
        }
    }

    #[test]
    fn match_intro_pending_dispatches_once_at_pristine_start() {
        let mut lc = fresh_lifecycle();
        lc.match_intro_pending = true;
        assert!(consume_match_intro_pending(&mut lc, 1, 0, 0));
        assert!(!lc.match_intro_pending);
        assert!(lc.welcome_played);
        assert!(!consume_match_intro_pending(&mut lc, 1, 0, 0));
    }

    #[test]
    fn match_intro_pending_waits_for_pristine_state() {
        let mut lc = fresh_lifecycle();
        lc.match_intro_pending = true;
        assert!(!consume_match_intro_pending(&mut lc, 1, 1, 0));
        assert!(lc.match_intro_pending);
        assert!(!lc.welcome_played);
        assert!(consume_match_intro_pending(&mut lc, 1, 0, 0));
    }

    #[test]
    fn match_intro_pending_abandoned_after_first_delivery() {
        let mut lc = fresh_lifecycle();
        lc.match_intro_pending = true;
        lc.deliveries_completed = 1;
        assert!(!consume_match_intro_pending(&mut lc, 1, 1, 4));
        assert!(!lc.match_intro_pending);
        assert!(!lc.welcome_played);
    }

    #[test]
    fn lifecycle_sets_match_intro_pending_on_rematch() {
        let mut history = CommentaryHistory {
            lifecycle: {
                let mut lc = fresh_lifecycle();
                lc.match_intro_pending = false;
                lc.welcome_played = true;
                lc.intro_open = false;
                lc.deliveries_completed = 42;
                lc
            },
            striker_runs: 87,
            team_runs: 120,
            consecutive_dots: 2,
            ..Default::default()
        };
        reset_commentary_history_for_match_session(&mut history, [0, 1], 20);
        assert!(history.lifecycle.match_intro_pending);
        assert!(history.lifecycle.intro_open);
        assert!(!history.lifecycle.welcome_played);
        assert_eq!(history.lifecycle.deliveries_completed, 0);
    }

    #[test]
    fn welcome_only_at_pristine_match_start() {
        let lc = fresh_lifecycle();
        assert!(should_play_welcome(&lc, 1, 0, 0));
    }

    #[test]
    fn welcome_not_after_first_delivery() {
        let mut lc = fresh_lifecycle();
        lc.deliveries_completed = 1;
        assert!(!should_play_welcome(&lc, 1, 1, 4));
    }

    #[test]
    fn welcome_not_when_already_played() {
        let mut lc = fresh_lifecycle();
        lc.welcome_played = true;
        assert!(!should_play_welcome(&lc, 1, 0, 0));
    }

    #[test]
    fn welcome_not_on_second_innings_ready() {
        let lc = fresh_lifecycle();
        assert!(!should_play_welcome(&lc, 2, 0, 0));
    }

    #[test]
    fn welcome_not_after_runs_on_board() {
        let lc = fresh_lifecycle();
        assert!(!should_play_welcome(&lc, 1, 0, 1));
    }

    #[test]
    fn lifecycle_resets_on_rematch_same_setup() {
        let mut history = CommentaryHistory {
            lifecycle: {
                let mut lc = fresh_lifecycle();
                lc.welcome_played = true;
                lc.deliveries_completed = 42;
                lc
            },
            striker_runs: 87,
            team_runs: 120,
            consecutive_dots: 2,
            ..Default::default()
        };
        reset_commentary_history_for_match_session(&mut history, [0, 1], 20);
        assert!(!history.lifecycle.welcome_played);
        assert_eq!(history.lifecycle.deliveries_completed, 0);
        assert_eq!(history.striker_runs, 0);
        assert_eq!(history.team_runs, 0);
        assert_eq!(
            history.lifecycle.match_fp,
            Some(MatchFingerprint {
                teams: [0, 1],
                overs: 20,
            })
        );
    }

    #[test]
    fn result_pause_entry_once_per_occurrence() {
        let mut in_rp = false;
        // First wide: enter ResultPause
        assert!(result_pause_entered(in_rp, true));
        in_rp = true;
        // Held frames in same pause
        assert!(!result_pause_entered(in_rp, true));
        // Leave pause
        in_rp = false;
        assert!(!result_pause_entered(in_rp, false));
        // Second wide with same legal_balls — new pause occurrence
        assert!(result_pause_entered(in_rp, true));
        in_rp = true;
        assert!(!result_pause_entered(in_rp, true));
    }

    #[test]
    fn consecutive_result_pause_entries_are_distinct() {
        let mut in_rp = false;
        for _ in 0..3 {
            assert!(result_pause_entered(in_rp, true));
            in_rp = true;
            assert!(!result_pause_entered(in_rp, true));
            in_rp = false;
        }
    }

    #[test]
    fn result_priority_beats_welcome_in_scheduler() {
        assert!(scheduler_should_accept(None, CommentaryPriority::Welcome));
        assert!(scheduler_should_accept(
            Some(CommentaryPriority::Welcome),
            CommentaryPriority::Result
        ));
        assert!(!scheduler_should_accept(
            Some(CommentaryPriority::Result),
            CommentaryPriority::Welcome
        ));
    }

    #[test]
    fn result_priority_beats_phase_in_scheduler() {
        assert!(scheduler_should_accept(
            Some(CommentaryPriority::Phase),
            CommentaryPriority::Result
        ));
        assert!(!scheduler_should_accept(
            Some(CommentaryPriority::Result),
            CommentaryPriority::Phase
        ));
    }

    #[test]
    fn priority_for_category_mapping() {
        assert_eq!(
            priority_for_category("welcome"),
            CommentaryPriority::Welcome
        );
        assert_eq!(
            priority_for_category("over_complete"),
            CommentaryPriority::Phase
        );
        assert_eq!(priority_for_category("four"), CommentaryPriority::Result);
        assert_eq!(
            priority_for_category("context_fifty"),
            CommentaryPriority::Result
        );
    }
}
